### ISSUE TITLE
TypeError: Unrecognized 'struct kmem_cache': could not find member 'cpu_cache'

### ISSUE THREAD

**Issue by nkaretnikov** [crash-python/crash-python#43]
pycrash was installed from a binary package on openSUSE as described [here](https://github.com/crash-python/crash-python/issues/42#issue-589704073).

Tried it on an ELF Ubuntu dump generated with `makedumpfile`. I used these options in
`/etc/default/kdump-tools`:
```
MAKEDUMP_ARGS="-E -d 31"
```

This dump loads fine in crash (`lsmod` and `ps` commands work).

BTW: Is pycrash even supposed to work on many different images? Is it only for SUSE? Or is this still work in progress?

Error:
```
# pycrash vmlinux-5.0.0-38-generic dump.202003130141
crash-python initializing...
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "/usr/lib/python3.6/site-packages/crash/session.py", line 30, in __init__
    autoload_submodules('crash.commands')
  File "/usr/lib/python3.6/site-packages/crash/infra/__init__.py", line 26, in autoload_submodules
    x = importlib.import_module(modname)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/crash/commands/kmem.py", line 28, in <module>
    from crash.types.slab import kmem_cache_get_all, kmem_cache_from_name
  File "/usr/lib/python3.6/site-packages/crash/types/slab.py", line 684, in <module>
    KmemCache.setup_alien_cache_type)])
  File "/usr/lib/python3.6/site-packages/crash/util/symbols.py", line 324, in __init__
    super().__init__(TypeCallback, cbs)
  File "/usr/lib/python3.6/site-packages/crash/util/symbols.py", line 319, in __init__
    t = cls(cb[0], cb[1])
  File "/usr/lib/python3.6/site-packages/crash/infra/lookup.py", line 194, in __init__
    self.connect_callback()
  File "/usr/lib/python3.6/site-packages/crash/infra/callback.py", line 61, in connect_callback
    completed = self.callback(result)
  File "/usr/lib/python3.6/site-packages/crash/infra/lookup.py", line 70, in callback
    return self._callback(result)
  File "/usr/lib/python3.6/site-packages/crash/types/slab.py", line 328, in check_kmem_cache_type
    cls.percpu_name = find_member_variant(gdbtype, ['cpu_cache', 'array'])
  File "/usr/lib/python3.6/site-packages/crash/util/__init__.py", line 305, in find_member_variant
    .format(str(gdbtype), variants[0]))
TypeError: Unrecognized 'struct kmem_cache': could not find member 'cpu_cache'
/tmp/crash.fpPmaG/gdbinit:65: Error in sourced command file:
Error while executing Python code.
```

**Comment by tehcaster** [comment]
Yes, pycrash can indeed be considered work in progress. There's certainly no intention to limit in on SUSE kernels, but as the developers are mostly from the company, features are naturally motivated mainly by debugging our kernels.
This particular issue will be resolved once SLUB support is merged, it's now in my branch https://github.com/tehcaster/crash-python/tree/kmem-slub
You can do a local clone and use the ./crash.sh from there on top of the rpm's you installed.

**Comment by tehcaster** [comment]
SLUB support has been merged some time ago, closing, thanks!
