### ISSUE TITLE
Python exception "AttributeError: module 'gdb' has no attribute 'Register'"

### ISSUE THREAD

**Issue by agentzh** [crash-python/crash-python#44]
First of all, thank you for creating this debugger!

I'm trying out pycrash on Fedora 30 using the latest master branches of libdumpfile and this project but hit by a weird Python exception:

```console
$ ./pycrash -m ~/tmp ~/tmp/./usr/lib/debug/lib/modules/2.6.32-754.24.3.el6.x86_64/vmlinux ~/tmp/bad-centos6-test2.core
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "./build/lib/crash/__init__.py", line 5, in <module>
    import kdump.target
  File "./build/lib/kdump/target.py", line 16, in <module>
    TargetFetchRegisters = Callable[[gdb.InferiorThread, gdb.Register], None]
AttributeError: module 'gdb' has no attribute 'Register'
./test-gdb-compatibility.gdbinit:16: Error in sourced command file:
Error while executing Python code.
fatal: crash-python cannot initialize
```

How to work around this please? Thanks for your attention!

**Comment by tehcaster** [comment]
Hi, sounds like you don't have the patched gdb that's required?

**Comment by problame** [comment]
I am hitting the same issue on Debian bullseye. 

```
cs@debian-zfs-devel:[~/src/crash-python]: dpkg -l gdb
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  gdb            10.1-1.7     amd64        GNU Debugger
```

The docs only mention that gdb with python extensions and python >= 3.6 is required. AFAIK that is the case on my system. Still, I get that error.

**Comment by tehcaster** [comment]
It's a bit unclear but it doesn't mean the standard python API in gdb, but extended with more patches, with a link to https://github.com/crash-python/gdb-python/tree/gdb-9.1-target that has them.
